# Generated by Django 5.1.7 on 2025-04-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_max_members_project_members_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'To be started'), (1, 'In progress'), (2, 'Completed')], default=0),
        ),
    ]
